i=[]
for l in range(5):
    i.append(int(input()))
print(i)
a=["pnone","laptop","tv"]
print(type(a))
print(a[2])
print(a[1:3])
a[2]="mouse"
print(a)
a[1:3]="keyboard","wire"
print(a)
a.append("calculator")
print(a)
b=["java","phyton","c"]
a.append(b)
print(a)
a.clear()
print(a)
c=b.copy()
print(b,c,sep="\n")
l1=[1,2,3,4,5,6,7,1,2,4,1,1]
s1=l1.count(1)
print(s1)
b.extend(l1)
print(b)
s3=b.index(1)
print(s3)
l1.insert(1,999)
print(l1)
l1.pop(1)
print(l1)
l1.remove(1)
print(l1)
l1.sort()
print(l1)
l1.sort(reverse= True)
print(l1)
b.reverse()
print(b)
l2=["q","w"]
l3=[1,2,3,4]
s4=l2+l3
print(s4)
s5=l3*3
print(s5)
l4=[3,3,3,3]
s6=list(map(lambda m,n:(m+n),l3,l4))
print(s6)