a=2
b=2.45
c="zim"
x=["zim","rakib","rana"]
y={"zim","rakib","rana"}
z=("zim","rakib","rana")
i=2j
j=range(6)
k={"Name":"zim","Age":23}
l=frozenset({"zim","rakib","rana"})
d1=True
d2=b"Zim"
d3=bytearray(10)
d4=memoryview(bytes(10))
print(type(a))
print(type(b))
print(type(c))
print(type(x))
print(type(y))
print(type(z))
print(type(i))
print(type(j))
print(type(k))
print(type(l))
print(type(d1))
print(type(d2))
print(type(d3))
print(type(d4))
print(d4)
print(d3)
print(d2)